spring:
  application:
    name: weatherAPI
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/weather
    username: weather
    password: weather

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000        # 커넥션 타임아웃 (5초)
      idle-timeout: 600000            # 유휴 타임아웃 (10분)
      max-lifetime: 1800000           # 최대 생명 주기 (30분)
      validation-timeout: 5000        # 유효성 검사 타임아웃 (5초)
      validation-query: SELECT 1     # 커넥션 유효성 검사 쿼리
      test-while-idle: true

  jpa:
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

